### PR TITLE
Show division outline on map

### LINKED ISSUE #229: Report overview - Administrative division polygon
Item 6.

### PR DESCRIPTION
**Pull request by pgiraud**
Fixes #229.
@elemoine it would be nice if you could have a review when you're back.

### CODE REVIEW

**Comment by pgiraud** [comment]
We unfortunately have an issue with OL3.
https://github.com/openlayers/ol3/issues/3941

**Comment by elemoine** [comment]
> We unfortunately have an issue with OL3.
> openlayers/ol3#3941

The issue will be fixed in 3.8.0 (https://github.com/openlayers/ol3/pull/3883). So I guess we can wait a bit and use v3.8.0 instead of v3.7.0.

**Comment by pgiraud** [comment]
According to the discussion we just had with @elemoine, this should be simplified. There's no real advantage to use 2 different vector layers.

**Comment by pgiraud** [comment]
Please review again.

**Comment by pgiraud** [comment]
I prefer to merge without any new review. Please reopen if you see issues.

**Pull request merged**
