### PR TITLE
Make it possible to use development.ini with modwsgi

### PR DESCRIPTION
**Pull request by elemoine**
This PR makes it possible to use `development.ini` with Apache mod_wsgi. It also makes it possible to use a local ini file for specific settings, such as `sqlalchemy.url`. The branch also includes various fixes and cleanups.

Example of a `local.ini` file:

```
[app:main]
sqlalchemy.url = postgresql://www-data:www-data@localhost:9999/thinkhazard
```

Please review.

### CODE REVIEW

**Comment by elemoine** [comment]
@marionb, when this is merged, you'll need to edit `/var/www/vhosts/wb-thinkhazard/conf/mbaumgartner.conf` and replace the `Include` line with this one:

```
Include /home/mbaumgartner/thinkhazard/.build/apache-development.conf
```

**Comment by pgiraud** [comment]
Don't you need to add `local.ini` to the git ignores?

**Comment by elemoine** [comment]
Well I could. But even the name of the local file is configurable.

**Comment by pgiraud** [comment]
Please merge.

**Comment by elemoine** [comment]
`local.ini` added to `.gitignore`.

**Pull request merged**
