### PR TITLE
Show application version in about page

### PR DESCRIPTION
**Pull request by pgiraud**
Works with "git describe" and should show tags when annotated tags are
available.

### CODE REVIEW

**Comment by pgiraud** [comment]
Fixes #547

**Comment by arnaud-morvan** [comment]
I don't really understand why you make a filter for this. This could be executed in about view.

**Comment by pgiraud** [comment]
> I don't really understand why you make a filter for this. This could be executed in about view.

Because I don't know how I can do the following in a jinja2 template:
```python
import subprocess
label = subprocess.check_output(['git', 'describe', '--always'])
```

**Comment by arnaud-morvan** [comment]
I was thinking to call git describe in view and return the label to the template.

**Comment by pgiraud** [comment]
It's not only one view.

**Comment by arnaud-morvan** [comment]
Thanks, it looks good to me now.

**Pull request merged**
