### PR TITLE
Use app init time as last_modified header

### PR DESCRIPTION
**Pull request by arnaud-morvan**

### CODE REVIEW

**Comment by pgiraud** [comment]
Can you please rebase?

**Comment by arnaud-morvan** [comment]
Done

**Comment by pgiraud** [comment]
Looks good to me. Please merge.

**Comment by pgiraud** [comment]
This was actually a bad idea since we can't ensure that the init time is shared between all the wsgi processes. This results in resources being randomly considered as modified or not depending on which processed is used.
Reverting.

**Pull request merged**
