### PR TITLE
Use docker cache on CI

### PR DESCRIPTION
**Pull request by arnaud-morvan**
TODO: create the `camptocamp/thinkhazard-build repository` on docker hub

### CODE REVIEW

**Comment by tonio** [comment]
https://hub.docker.com/r/camptocamp/thinkhazard-build is up with permissions set.

**Comment by arnaud-morvan** [comment]
@tonio : apparently I do not have push rights, maybe it would simplify things to give me admin rights.

**Comment by arnaud-morvan** [comment]
Sorry it's build on docker hub but builder actually in makefile. Will change this in sources.

**Comment by arnaud-morvan** [comment]
Seems this has no effect on github CI.

**Pull request closed without merging**
