### PR TITLE
GPL v3 license

### PR DESCRIPTION
**Pull request by fvanderbiest**
Related issue is https://github.com/GFDRR/thinkhazard/issues/133

### CODE REVIEW

**Comment by pgiraud** [comment]
Instead of having specifying the authors for each file, I'd use an AUTHORS.txt file.
It should be much easier to maintain.

**Comment by pgiraud** [comment]
Also, the year should be 2016 not 2015.

**Comment by gurneyalex** [comment]
@pgiraud you may want to use 2015-2016 if the project started last year.

Authors / Contributors can be maintained in an external file, yes. 

You also want to update setup.py with the license / copyright information. And the MANIFEST.in too (or check that the license file  and contributors files are indeed included in the tarball).

**Comment by fvanderbiest** [comment]
> Also, the year should be 2016 not 2015.

The year is ```2015-``` which is supposed to mean: "from 2015 on"
Not sure it is valid though.

**Comment by gurneyalex** [comment]
@fvanderbiest Does not work like that. The year is the year of publication of the version of the work. So 2016 in this case. If you make a significant change next year, you wlll be entitled to update the date to 2017. 

The year is used to find out when a version falls in the public domain according to local laws. 

As ususal::

    from std_disclaimers import ianal

**Comment by pgiraud** [comment]
We can merge.

**Pull request merged**
