### PR TITLE
Change style for link on map

### PR DESCRIPTION
**Pull request by tonio**
screenshot from 2017-06-15 10-39-25

Thin black line could be confusing, what about a dashed one?

### CODE REVIEW

**Comment by stufraser1** [comment]
Dashed lines should be reserved for disputed borders. Didn't we have disputed borders represented as dashed lines in a previous dev version? If so this border style should be reinstated. Example of disputed border is jammu and kashmir. Gaul files have a field stating whether an adm unit is disputed or not. Please confirm whether you have a previous dev version / basemap in v2 dev that included such borders as dashes.

**Comment by tonio** [comment]
That was previous style for disputed borders:
screenshot from 2017-06-19 15-07-11

It seems to have disappear in the new one:
screenshot from 2017-06-19 15-07-41

I can change «Go to» links to what was requested first, will look like: 
screenshot from 2017-06-19 15-04-36

**Comment by fjacon** [comment]
@stufraser1 :

- is Antoine's proposal OK ? (3rd picture)
- For disputed boundaries, the mapbox style has to be modified.

**Comment by stufraser1** [comment]
Antoines proposal looks ok. I still have some concern that the non select Ted boundaries look like rivers, but maybe this will appear ok when I add in boundaries to the basemap. I'll have to supply a new basemap later this week

**Comment by fjacon** [comment]
@tonio so you can go ahead with merging this PR.

**Comment by tonio** [comment]
Deployed on integration

**Pull request merged**
