### PR TITLE
LESS optimizations

### PR DESCRIPTION
**Pull request by pgiraud**
The goal of this pull request is to get a smaller css file by removing any dependence on openlayers and by loading only the classes we use from bootstrap.

### CODE REVIEW

**Comment by ingenieroariel** [comment]
If we are not using open layers anymore, how are the maps being loaded?

**Comment by pgiraud** [comment]
@ingenieroariel because we don't need any interaction on the map (no zoom or pan) we decided to get rid of OpenLayers. The map will be request to the service as a simple image.
This will eventually lighten the code and decrease the application complexity.

**Comment by ingenieroariel** [comment]
Thanks for the explanation Pierre. It makes sense.

**Comment by elemoine** [comment]
We still load ol in the page: https://github.com/GFDRR/thinkhazard/blob/master/thinkhazard/templates/report.jinja2#L101-L107. This should be removed as well.

**Comment by elemoine** [comment]
The OpenLayers 3 code was removed with https://github.com/GFDRR/thinkhazard/pull/68. Please rebase this and merge. Thanks.

**Pull request merged**
