### PR TITLE
Updating the about page

### LINKED ISSUE #566: Add images to About page
Logos and coverage map to be added to about page - please see attached zips, and associated text:

The following organizations have contributed data and / or expert input to the development of this tool:
[Logo.zip](https://github.com/GFDRR/thinkhazard/files/199780/Logo.zip)

ThinkHazard! holds local data for the countries displayed in this map. Global data is available for river flood, earthquake, cyclone, water scarcity, and landslide.
[Data_Holdings-01.zip](https://github.com/GFDRR/thinkhazard/files/199779/Data_Holdings-01.zip)

### PR DESCRIPTION
**Pull request by pgiraud**
Fixes #566

### CODE REVIEW

**Comment by pgiraud** [comment]
@stufraser1 Can you please check out this [demo](http://wb-thinkhazard.dev.sig.cloud.camptocamp.net/pierre/wsgi/report/116-indonesia)?

**Comment by stufraser1** [comment]
I receive internal server error at the moment. Can this demo be viewed on the thinkhazard.org preview, or on the beta2 site?
The link you gave me was /pierre/wsgi, and I can't access it

**Comment by pgiraud** [comment]
@stufraser1 This can be tested on the integration server.
http://int.thinkhazard.org

Please confirm that it's looking good.

**Comment by stufraser1** [comment]
Looks good - there is a bit of repeated text now we've added the logos too.
We can remove the paragraph: 'ThinkHazard! was developed by the Global Facility for Disaster Reduction and Recovery (GFDRR) Innovation Lab, in partnership with BRGM (French geological survey), Camptocamp and Deltares. Hazard datasets have been provided by UNISDR, Impact Forecasting, SSBN, PRACFI, The World Bank, IVM-VU and USGS.'

**Comment by pgiraud** [comment]
Done.
I also moved the paragraph talking about source code to the bottom.
Merging.

**Pull request merged**
