### PR TITLE
Update divisions

### PR DESCRIPTION
**Pull request by pgiraud**
This pull request's goal is to update the administrative divisions:
 - some divisions names have been updated,
 - names in French and Spanish have been added for level 0 when available,
 - `import_divs` script has been updated to import directly from shapefile,
 - some divisions have change (Kosovo for example).

### CODE REVIEW

**Comment by pgiraud** [comment]
@stufraser1 
I finally managed to get something working to update the administrative divisions. It took more work than expected. The good thing is that it was worth since it was required for the names translations.

I invite you to go the integration instance and check if everything works as expected.
http://int.thinkhazard.org/

This instance runs a copy of the production database with the update.
I manually change (via the admin interface) the climate change recommendation for Landslide so that it applies for Kosovo as well.

Once you think this works as expected, I'll deploy the code and database on the production server.

**Comment by stufraser1** [comment]
I'm currently unable to view http://int.thinkhazard.org/ due to 'internal server error'

**Comment by pgiraud** [comment]
Can you please try again?

**Comment by stufraser1** [comment]
Kosovo works well. Please deploy as we need to get that live ASAP.

**Comment by pgiraud** [comment]
Production is up-to-date!

**Comment by stufraser1** [comment]
Thank you!

**Pull request merged**
