### PR TITLE
Add datamart model

### PR DESCRIPTION
**Pull request by elemoine**
This PR implements the datamart model  as discussed with BRGM. Still WIP and discussed with BRGM.

### CODE REVIEW

**Comment by ingenieroariel** [comment]
After reading the PR, some questions arised:

  * The TermStatus seems to be linked in quite a few other tables but it is not clear to me what it does.
  * It seems Recommendation and AdditionalInfo are not linked in any of the other tables.

In any case I am :+1: for merging this, but would like to have a technical meeting about the object relational mapping in the DataMart during the meetings in May.

**Comment by elemoine** [comment]
> It seems Recommendation and AdditionalInfo are not linked in any of the other tables.

They are, through n:n relation tables.

**Comment by elemoine** [comment]
The PR is ready for review.

As a summary, this is what the PR includes:

* Implement with SQLA classes the "datamart" data model as designed by BRGM and Camptocamp.
* Make the "search admin divisions" web service use the new data model.

**Comment by fvanderbiest** [comment]
LGTM

**Pull request merged**
