### PR TITLE
Added geonode regions of the world to the csv. This fixes #441

### LINKED ISSUE #441: Regions only include countries
With the pull request https://github.com/GFDRR/thinkhazard/pull/427, we can now link regions (as set in geonode) to GAUL administrative divisions.
In the .csv file provided by @javierdaza, only the regions that correspond to a country in GAUL are listed. We also need to link regions that are not countries to GAUL codes.

For example for Europe, we need as many lines in the CSV as countries in Europe (one for France, one for Spain, etc...)

First Header | Region id | GAUL code
------------ | -------------| --------
Europe | 5 | 85
Europe | 5 | 229
... | ... | ...

Does it make sense? Are you able to extract such information?

cc @ingenieroariel

### PR DESCRIPTION
**Pull request by javierdaza**
Still missing 4 regions: Channel islands, Aland islands, Saint-Barthelemey and Saint Martin.

### CODE REVIEW

**Comment by pgiraud** [comment]
Hi. Thanks a lot for this new version.
I notice one (and only one) occurrence of "Global". Is it expected?

**Comment by fvanderbiest** [comment]
Agreed with @pgiraud, there should be as many "global" lines as there are countries

**Comment by ingenieroariel** [comment]
Definitely.

@javierdaza Can you check what happened and also sort the regions by name
(so that they are grouped together).

@pgiraud Should we add a fourth column with the GAUL name to help us verify?

Also "Africa", "America", "Asia" do not even apear on the list.

-a

**Comment by fvanderbiest** [comment]
>  Should we add a fourth column with the GAUL name to help us verify?

Would be nice indeed.
It shouldn't break our implementation.

**Pull request merged**
