### PR TITLE
Remove french word "sig"

### PR DESCRIPTION
**Pull request by fvanderbiest**
Please review

### CODE REVIEW

**Comment by pgiraud** [comment]
Will this work on our demo server?

**Comment by fvanderbiest** [comment]
Indeed, this folder has to be created by root.

**Comment by fvanderbiest** [comment]
OKay, maybe it should be /tmp by default.
Everyone will expect a different location for production (eg: ```/var/www/vhosts/wb-thinkhazard/private/data``` in our case)

**Comment by pgiraud** [comment]
OK for /tmp.

**Comment by fvanderbiest** [comment]
Done.

**Pull request merged**
